### ISSUE TITLE
Letting openshft-ovs play nice with processes using openvswitch outside the cluster

### ISSUE THREAD

**Issue by midekra** [openshift/cluster-network-operator#122]
I was wondering if it's possible to use openvswitch outside the cluster without openshift-ovs complaining with error: "warning: Another process is currently managing OVS, waiting 15s ". After x tries the pod restarts.

In my specific situation i'm deploying openstack nova/neutron with openvswitch as pods in openshift. Everything seems to be working and i'm using de ovsdb tcp connection to the node openvswitch configuration, but openshift-sdn/ovs complains about that another process is managing OVS (which is true because of neutron openvswitch). De openshift-ovs pod then restarts and causes a loop.
Like I said, everything seems to be working but the pod openshift-ovs pods keeps restarting.

Any advice or pointers?

**Comment by squeed** [comment]
The operator can use an already-running openvswitch on the host - that's useExternalOpenvswitch. However, it's *not* supported, and we *definitely* don't support it with existing flow rules inside. It is intended for people who run custom openvswitch installations with hardware acceleration.

So you're welcome to try, but I would be surprised if it works.

**Comment by danwinship** [comment]
We now only support using the system OVS. We still don't support trying to hack openshift-sdn/ovn-kubernetes's OVS to do something other than what openshift-sdn/ovn-kubernetes expects.
