### ISSUE TITLE
[RFE] Provide Support for Third Party Network Providers

### ISSUE THREAD

**Issue by vareti** [openshift/cluster-network-operator#200]
As of today, CNO only supports `OpenShiftSDN`, `OVNKubernetes`, `Kuryr` and `Raw` network types. `OpenShiftSDN` is the default if nothing is specified. I could not find a way for CNO to not deploy CNI plugin and other network components. This results in a conflict when third party network providers  deploy their own set of network components to manage networking in an OpenShift cluster.

It would be nice if there is a way to disable deploying default network components and let third party providers to manage OpenShift cluster network.

**Comment by squeed** [comment]
Specifying a DefaultNetworkType that CNO doesn't understand means that it will not deploy a networking provider. So this should already be what you want...

**Comment by vareti** [comment]
Thanks for the clarification. This is helpful.

I do have question on disabling multus though. I see that I can be disabled by setting the [DisableMultiNetwork ](https://github.com/openshift/api/blob/master/operator/v1/types_network.go#L58) parameter to `true`. But I am not sure if this is exposed in install config file. [Installer](https://github.com/openshift/installer) seems to be create `Network.config.openshift.io` custom resource in which [`NetworkSpec`](https://github.com/openshift/api/blob/master/config/v1/types_network.go#L28) does not have `DisableMultiNetwork` option? Same applies to `kube-proxy` too?

Kindly let me know if I am missing something basic, again...

**Comment by squeed** [comment]
It's not a stupid question. There is the opportunity to supply your own network configuration during installation. It does require a few additional steps, but it does work:

https://docs.openshift.com/container-platform/4.1/installing/installing_aws/installing-aws-network-customizations.html#modifying-nwoperator-config-startup_installing-aws-network-customizations

**Comment by vareti** [comment]
Thanks for the link.

It may not matter but I am trying an UPI install but not an AWS install. I guess the manifests generated from install command can also be used with UPI install.

I will try this approach and get back to you.

**Comment by vareti** [comment]
Closing this as the questions are answered. Thanks @squeed
