### ISSUE TITLE
the CR network-attachment-definitions did not created after the cluster network updated

### ISSUE THREAD

**Issue by hchenxa** [openshift/cluster-network-operator#383]
I try to create the additional network follow the document https://docs.openshift.com/container-platform/4.2/networking/multiple-networks/configuring-macvlan.html#configuring-macvlan on OCP 4.2, based on the document describe, after the cluster network CR updated by adding the additional network, the CNO should create the related network-attachment-definition CR, but in my test environment, the CR did not created after I update the cluster network for a long time.

**Comment by hchenxa** [comment]
here is my cluster network spec:

**Comment by danwinship** [comment]
try `oc logs` on the cluster-network-operator pod to see if it logged any errors?
