### ISSUE TITLE
Openshift-sdn listens on undeclared ports

### ISSUE THREAD

**Issue by squeed** [openshift/cluster-network-operator#40]
As a general rule, we should declare all ports for processes that run in host-network, so we can easily catch conflicts. I ran a quick auditing script:

```console
[root@test1-worker-0-rpzmc core]# ~core/sockaudit
pod sdn-pzh2f process openshift-sdn listening on NotDeclared port 31712
pod sdn-pzh2f process openshift-sdn listening on NotDeclared port 30119
pod sdn-pzh2f process openshift-sdn listening on NotDeclared port 10256
pod sdn-pzh2f process openshift-sdn listening on NotDeclared port 32562
```

We need to either declare these ports or stop listening.

**Comment by danwinship** [comment]
The 3xxxx ports are probably random/ephemeral. (None of them appear in the sources.)

**Comment by squeed** [comment]
I'm silly. They are kube-proxy holding NodePorts so nothing else binds the port.
