### ISSUE TITLE
On OCP4.2 Multitenant mode, can't change kube-system's NETID. 

### ISSUE THREAD

**Issue by haoqing0110** [openshift/cluster-network-operator#403]
I deployed an OCP 4.2 cluster with Multitenant mode, the default NETID of kube-system is 1. 
```
# oc get netnamespaces kube-system
NAME          NETID   EGRESS IPS
kube-system   1
```
I try to make kube-system global with below commands : 
```
oc adm pod-network make-projects-global kube-system
```
```
oc adm pod-network join-projects --to=default kube-system
```
but seems neither commands work, wait for a while, the NETID is reset to 1 again. 

QUESTION, how can I change kube-system NETID to 0 in Multitenant mode ?

**Comment by danwinship** [comment]
You can't. Why are you trying to?

**Comment by haoqing0110** [comment]
@danwinship I have some app deployed in kube-system, and need to reach other namespace's pod, but it failed when I set multitenant mode. If can't change  kube-system NETID to 0, that would be a problem for me.

**Comment by haoqing0110** [comment]
@danwinship based on my above needs, 3 further questions, thanks a lot for answering!

1. In OCP 4.2, I didn't see any pods deployed in kube-system by default installation, any reason set kube-system NETID to 1 in multitenant mode ? 
2. And is that fine to submit a PR to remove [kube-system](https://github.com/openshift/cluster-network-operator/blob/master/bindata/network/openshift-sdn/004-multitenant.yaml#L77) from `004-multitenant.yaml`, as kube-system is not an OpenShift related namespace per my understanding, set  NETID to 1 in multitenant mode is strange to me. 
3. If answer to 2 is no, do cluster-network-operator has any plan to make 004-multitenant.yaml configurable ?

**Comment by danwinship** [comment]
I don't remember exactly what is/was there that resulted in us grouping it with the other netid 1 namespaces. You'd have to look through the git history / old bugs.

No, we are not going to make it configurable. In general, multitenant mode is deprecated and people should be moving to networkpolicy.

**Comment by haoqing0110** [comment]
@danwinship thanks !
Just go through the code history, seems : 
1. kube-system is original used for etcd, so add it to control panel in the first PR https://github.com/openshift/cluster-network-operator/pull/82
2. Then etcd moved to openshift-etcd namespace in https://github.com/openshift/cluster-network-operator/pull/224 , but don’t see why left kube-system there. 

@danwinship Will multitenant mode be deprecated in latest release? As can’t modify kube-system NETID blocks my current apps, so need a fix. 

@rcarrillocruz  could you help confirm why leave kube-system in control panel? is that fine to remove it ? (If yes, I can help prepare a PR).
