### ISSUE TITLE
Fix the startup script in the ovs daemonset for openshift-sdn to be agnostic of the bridge options that openshift-sdn pod sets

### ISSUE THREAD

**Issue by abhat** [openshift/cluster-network-operator#555]
Startup script changes in #524 adds a bridge to ovsdb to restore flows with some specific bridge options. This creates a maintainability issue.

If the options on the bridge change in openshift-sdn, the daemonset script needs to be updated. This issue is to track not exposing openshift-sdn specific bridge configuration options from the start-up script.

**Comment by danwinship** [comment]
no longer relevant
