### ISSUE TITLE
kube-proxy cluster-cidr is omitted breaking external service access when multiple cluster CIDRs are provided

### ISSUE THREAD

**Issue by matthewdupre** [openshift/cluster-network-operator#642]
This line here: https://github.com/openshift/cluster-network-operator/blob/master/pkg/network/kube_proxy.go#L45 doesn't pass a cluster-cidr to kube-proxy when the number of ClusterNetworks isn't one.  Omitting this field means services can't be accessed from outside the cluster.

The ClusterNetworks are immutable, so if the user does configure two and later discover that they want to access services from outside the cluster, they won't be able to (and it's not easy to debug why).  It's sometimes better to set too small a cluster CIDR (leading to some unwanted NAT) than not set one at all - but probably not always.

When using Calico, for example, additional IP ranges can be given to pods beyond those configured here, so this ends up being a trap.  I feel like a validation failure if len() > 1 would be more helpful?  I'd also like to see the field be mutable (although I understand that perhaps OpenShift SDN can't support that yet?).

**Comment by squeed** [comment]
Now that kube-proxy has the local-detector, perhaps we should be configuring detection differently anyways. What would you suggest, @matthewdupre?

**Comment by danwinship** [comment]
Yes, for openshift-sdn we should probably pick a better local-detector. In the general case, we might want to expose that configuration a little bit better so that third-party plugins can make use of it correctly.

**Comment by danwinship** [comment]
/assign @tssurya 

I randomly noticed this issue lying around. Once kube-proxy implements the other local-detector modes we should make sure CNO lets you override `--detect-local-mode` usefully in the `KubeProxyConfig`, when using standalone kube-proxy.
