### ISSUE TITLE
Reconcile should only return an error on transient errors

### ISSUE THREAD

**Issue by danwinship** [openshift/cluster-network-operator#70]
If you return an error from `Reconcile`, the controller will keep retrying the request again (with a backoff):

    2019/01/22 09:50:45 Reconciling NetworkConfig.networkoperator.openshift.io default
    2019/01/22 09:50:45 Not applying unsafe change: invalid configuration: [cannot change ClusterNetworks]
    2019/01/22 09:50:46 Reconciling NetworkConfig.networkoperator.openshift.io default
    2019/01/22 09:50:46 Not applying unsafe change: invalid configuration: [cannot change ClusterNetworks]
    2019/01/22 09:50:49 Reconciling NetworkConfig.networkoperator.openshift.io default
    2019/01/22 09:50:49 Not applying unsafe change: invalid configuration: [cannot change ClusterNetworks]
    2019/01/22 09:50:54 Reconciling NetworkConfig.networkoperator.openshift.io default
    2019/01/22 09:50:54 Not applying unsafe change: invalid configuration: [cannot change ClusterNetworks]

If the configuration is invalid, then "not applying" is a *successful* reconciliation, so we should not be returning an error. (This probably applies to other cases as well.)

**Comment by squeed** [comment]
Yeah, I was trying to decide how exactly to capture that state. On the one hand, it's not successful, because it cannot bring the cluster to the state that matches input. On the other hand, the cluster's status is not incorrect.

@deads2k, thoughts? What should we do if the input is obviously wrong.

**Comment by danwinship** [comment]
well, ok, that's the question we'd had before about "what is the status if the network is functioning but does not match the current config object?"

one possibility is to call it both Available and Failing in that case...

**Comment by danwinship** [comment]
fixed by #115
