### ISSUE TITLE
"Running manually" instructions are incomplete

### ISSUE THREAD

**Issue by danwinship** [openshift/cluster-network-operator#71]
The current "Running manually against a test cluster" instructions are incomplete; you need to set (at least) `KUBERNETES_SERVICE_PORT` and `KUBERNETES_SERVICE_HOST` in the environment as well in order for the sdn-controller daemonset to function correctly. (Possibly others?)

**Comment by squeed** [comment]
No, that's it (for now). Those variables are just a stupid hack to get around bind-mounting the kubelet's kubeconfig everywhere.
