### ISSUE TITLE
multus takes a long time to deploy (!)

### ISSUE THREAD

**Issue by danwinship** [openshift/cluster-network-operator#96]
eg, from https://storage.googleapis.com/origin-ci-test/pr-logs/pull/21905/pull-ci-openshift-origin-master-e2e-aws/3736/artifacts/e2e-aws/pods/openshift-network-operator_network-operator-6568d54ddc-2j4pz_network-operator.log.gz:

    2019/02/11 19:08:37 Reconciling update to DaemonSet openshift-multus/multus
    time="2019-02-11T19:08:37Z" level=info msg="updated clusteroperator: &v1.ClusterOperator{ ... Status:v1.ClusterOperatorStatus{ ... Message:\"DaemonSet \\\"openshift-multus/multus\\\" is not available (awaiting 3 nodes) ...
    2019/02/11 19:09:35 Reconciling update to DaemonSet openshift-multus/multus
    time="2019-02-11T19:09:35Z" level=info msg="updated clusteroperator: &v1.ClusterOperator{ ... Status:v1.ClusterOperatorStatus{ ... Message:\"DaemonSet \\\"openshift-multus/multus\\\" is not available (awaiting 2 nodes) ...
    2019/02/11 19:09:41 Reconciling update to DaemonSet openshift-multus/multus
    time="2019-02-11T19:09:41Z" level=info msg="updated clusteroperator: &v1.ClusterOperator{ ... Status:v1.ClusterOperatorStatus{ ... Message:\"DaemonSet \\\"openshift-multus/multus\\\" is not available (awaiting 1 nodes) ...
    2019/02/11 19:09:54 Reconciling update to DaemonSet openshift-multus/multus
    time="2019-02-11T19:09:54Z" level=info msg="updated clusteroperator: &v1.ClusterOperator{ ... Status:v1.ClusterOperatorStatus{ Type:\"Available\", Status:\"True\"...

The multus pods appear to spend a lot of time in `CrashLoopBackoff`.

**Comment by danwinship** [comment]
oh:
    Generating Multus configuration file ...
    Error: Multus could not be configured: no master plugin was found.

so I guess it's waiting for SDN to finish setting up. Maybe it should poll rather than exiting with an error though, since the "backoff" part of "CrashLoopBackoff" will probably cause there to be a much-longer-than-necessary delay before the final successful run

**Comment by squeed** [comment]
I filed SDN-305 to track basically this issue too.

**Comment by danwinship** [comment]
Fixed a while back

**Comment by liliyongleo** [comment]
can you provide the solution how you fix this? thanks. I met the same problem
